### ISSUE TITLE
NEWS about 5.1000.9923.0

### ISSUE THREAD

**Issue by alexevictor** [sl4v3k/Shapr3d_crack#65]
Hi, any news when u have time to crack 5.1000.9923.0

Thnks

**Comment by sl4v3k** [comment]
Done, check repo please.

**Comment by sl4v3k** [comment]
Shouldnt it be 6.1xxxxx???

**Comment by Droppenstein** [comment]
> Done, check repo please.

Downloaded, did all the steps as described and no luck... says patched but limitations are still present

<img width="2194" height="936" alt="Image" src="https://github.com/user-attachments/assets/441fec70-e187-4242-a3e7-923eb97ba5fb" />

Also, if I try to create a new file while "the patch is applied" the program just closes

**Comment by sl4v3k** [comment]
what i see on image, must work...tested right now on m side and works fine...hmmm

**Comment by xiaxianguyue** [comment]
work well,thanks!

**Comment by Droppenstein** [comment]
> what i see on image, must work...tested right now on m side and works fine...hmmm

well happened to me with most of the lastest releases, says patched properly but still not working. also that thing about closing the program when trying to create a new file while patched

**Comment by sl4v3k** [comment]
do You have antyvirus installed, may block process memory injections....would You install UltraViewer and share desktop to me, i need to check with debugger otherwise

**Comment by Droppenstein** [comment]
> do You have antyvirus installed, may block process memory injections....would You install UltraViewer and share desktop to me, i need to check with debugger otherwise

no av and the same thing happens. i'm not at home right now, when i come back will install ultraviewer and give you access
